const games = [
    {
        id: "fff",
        title: "Рыбалка для Друзей",
        desc: "Рыбалка для Друзей - мобильный рыболовный симулятор! Можно играть как оффлайн, так и онлайн.",
        author: "evados",
        genre: "Симуляторы",
        rating: "4.4",
        minAndroid: "2.3.3",
        version: "1.22",
        screenshots: [
            "img/apps/screenshots/fff1.jpg",
            "img/apps/screenshots/fff2.jpg"
        ],
        img: "img/apps/icons/fff.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/fff.apk"
    },
    {
        id: "kutegram",
        title: "Kutegram",
        desc: "Kutegram это неофициальный кроссплатформенный клиент на основе Qt для Telegram.",
        author: "CRX",
        genre: "Мессенджеры",
        rating: "4.1",
        minAndroid: "2.3.0",
        version: "1.0.0",
        screenshots: [
            "img/apps/screenshots/kutegram1.jpg",
            "img/apps/screenshots/kutegram2.jpg",
            "img/apps/screenshots/kutegram3.jpg"
        ],
        img: "img/apps/icons/kutegram.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/kutegram.apk"
    },
    {
        id: "youtube",
        title: "YouTube",
        desc: "Погрузитесь в мир бесконечного контента с YouTube.",
        author: "FlashBack",
        genre: "Социальные сети",
        rating: "4.8",
        minAndroid: "2.2.0",
        version: "2.4.4",
        screenshots: [
            "img/apps/screenshots/youtube1.jpg",
            "img/apps/screenshots/youtube2.jpg"
        ],
        img: "img/apps/icons/youtube.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/youtube.apk"
    },
    {
        id: "minecraft",
        title: "Minecraft: Pocket Edition",
        desc: "Minecraft — это строительная игра жанра песочница.",
        author: "Mojang AB",
        genre: "Песочницы",
        rating: "4.3",
        minAndroid: "2.3.0",
        version: "0.8.1",
        screenshots: [
            "img/apps/screenshots/minecraft1.jpg",
            "img/apps/screenshots/minecraft2.jpg"
        ],
        img: "img/apps/icons/minecraft.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/minecraft.apk"
    },
    {
        id: "geometrydash",
        title: "Geometry Dash",
        desc: "Практически непроходимые испытания и безумная музыка.",
        author: "RobTop",
        genre: "Платформеры",
        rating: "4.4",
        minAndroid: "2.2.0",
        version: "1.0",
        screenshots: [],
        img: "img/apps/icons/geometrydash.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/geometrydash.apk"
    },
    {
        id: "angrybirds",
        title: "Angry Birds",
        desc: "Стреляйте птицами по укреплениям свиней.",
        author: "Rovio",
        genre: "Головоломки",
        rating: "4.0",
        minAndroid: "1.6.0",
        version: "1.6.0",
        screenshots: [],
        img: "img/apps/icons/angrybirds.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/angrybirds.apk"
    },
    {
        id: "subwaysurf",
        title: "Subway Surfers",
        desc: "Уворачивайтесь от поездов и собирайте монеты.",
        author: "Kiloo",
        genre: "Раннеры",
        rating: "4.6",
        minAndroid: "2.3.3",
        version: "1.24.0",
        screenshots: [],
        img: "img/apps/icons/subwaysurf.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/subwaysurf.apk"
    },
    {
        id: "pvsz",
        title: "Plants vs Zombies",
        desc: "Защитите свой дом от орд зомби.",
        author: "PopCap",
        genre: "Стратегии",
        rating: "4.9",
        minAndroid: "1.5.0",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/pvsz.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/pvsz.apk"
    },
    {
        id: "doodlejump",
        title: "Doodle Jump",
        desc: "Прыгай выше и выше!",
        author: "Lima",
        genre: "Платформеры",
        rating: "4.0",
        minAndroid: "2.3.3",
        version: "1.3",
        screenshots: [],
        img: "img/apps/icons/doodlejump.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/doodlejump.apk"
    },
    {
        id: "fruitninja",
        title: "Fruit Ninja",
        desc: "Режь фрукты и ставь рекорды.",
        author: "HalfBrick",
        genre: "Боевики",
        rating: "4.9",
        minAndroid: "2.3.3",
        version: "1.9.5",
        screenshots: [],
        img: "img/apps/icons/fruitninja.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/fruitninja.apk"
    },
    {
        id: "cuttherope",
        title: "Cut The Rope",
        desc: "Накорми Ам Няма конфетами!",
        author: "ZeptoLab",
        genre: "Головоломки",
        rating: "4.7",
        minAndroid: "1.6.0",
        version: "1.0.0",
        screenshots: [],
        img: "img/apps/icons/cuttherope.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/cutetherope.apk"
    },
    {
        id: "flappybird",
        title: "Flappy Bird",
        desc: "Расправь крылья и лети.",
        author: "DotGears",
        genre: "Боевики",
        rating: "5.0",
        minAndroid: "2.2.0",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/flappybird.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/flappybird.apk"
    },
    {
        id: "flashlight",
        title: "Фонарик",
        desc: "Простой и яркий фонарик.",
        author: "Devuni",
        genre: "Утилиты",
        rating: "5.0",
        minAndroid: "4.1.0",
        version: "5.4.1",
        screenshots: [],
        img: "img/apps/icons/flashlight.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/flashlight.apk"
    },
    {
        id: "chrome",
        title: "Google Chrome",
        desc: "Браузер от Google на основе Chromium.",
        author: "Google LLC",
        genre: "Браузеры",
        rating: "4.6",
        minAndroid: "4.0.1",
        version: "42.0",
        screenshots: [],
        img: "img/apps/icons/chrome.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/chrome.apk"
    },
    {
        id: "antutu",
        title: "AnTuTu Benchmark",
        desc: "Benchmark для тестирования устройства.",
        author: "AnTuTu",
        genre: "Утилиты",
        rating: "4.8",
        minAndroid: "2.3.0",
        version: "4.0",
        screenshots: [],
        img: "img/apps/icons/antutu.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/antutu.apk"
    },
    {
        id: "esfile",
        title: "ES Проводник",
        desc: "Мощный файловый менеджер.",
        author: "ES Global",
        genre: "Утилиты",
        rating: "4.4",
        minAndroid: "2.2.0",
        version: "4.0.26",
        screenshots: [],
        img: "img/apps/icons/esfile.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/esfile.apk"
    },
    {
        id: "j2meloader",
        title: "J2ME Loader",
        desc: "Запуск Java-игр на Android.",
        author: "Play Software",
        genre: "Эмуляторы",
        rating: "4.7",
        minAndroid: "2.3.0",
        version: "1.4.2",
        screenshots: [],
        img: "img/apps/icons/j2meloader.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/j2meloader.apk"
    },
    {
        id: "ibispaintx",
        title: "ibisPaint X",
        desc: "Приложение для рисования.",
        author: "ibis inc.",
        genre: "Редакторы",
        rating: "4.6",
        minAndroid: "4.0.1",
        version: "3.2.1",
        screenshots: [],
        img: "img/apps/icons/ibispaintx.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/ibispaintx.apk"
    },
    {
        id: "mobizen",
        title: "Mobizen",
        desc: "Запись экрана.",
        author: "RSUPPORT",
        genre: "Утилиты",
        rating: "4.2",
        minAndroid: "4.4.0",
        version: "3.10.7.4",
        screenshots: [],
        img: "img/apps/icons/mobizen.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/mobizen.apk"
    },
    {
        id: "tiktoklite",
        title: "TikTok Lite",
        desc: "Облегчённая версия TikTok.",
        author: "TikTok",
        genre: "Социальные сети",
        rating: "4.2",
        minAndroid: "4.4.0",
        version: "28.6.1",
        screenshots: [],
        img: "img/apps/icons/tiktoklite.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/tiktoklite.apk"
    },
    {
        id: "wdw",
        title: "Waving Droid Widget",
        desc: "Коллекция Android-виджетов.",
        author: "AJR",
        genre: "Виджеты",
        rating: "4.6",
        minAndroid: "2.2.0",
        version: "5.4",
        screenshots: [],
        img: "img/apps/icons/wdw.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/wdw.apk"
    },
    {
        id: "semkoed",
        title: "Семкоед",
        desc: "Фартовый нежданчик для басоты: теперь семкоед и на андроиде! Самый пацанский способ прожигать время в лоховозах, на метре и других тягомотинах. Суетите пацанчика, двигая по экрану пальцем и ловите семки ртом «на Пятаке», «Раёне», «в Инстике», «в Опорке», «Питейке» и в многих других козырных местах.",
        author: "Killa",
        genre: "Симуляторы",
        rating: "4.0",
        minAndroid: "3.2.0",
        version: "1.9.5",
        screenshots: [],
        img: "img/apps/icons/semkoed.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/semkoed.apk"
    },
    {
        id: "earntodie",
        title: "Earn To Die Lite",
        desc: "Earn to Die Lite — это увлекательная гоночная игра для Android, где вы должны ехать на своем автомобиле по опасным дорогам, попутно убивая зомби и зарабатывая деньги для улучшения своего автомобиля!",
        author: "NotDoppler",
        genre: "Боевики",
        rating: "4.3",
        minAndroid: "2.2.0",
        version: "1.0.19",
        screenshots: [],
        img: "img/apps/icons/earntodie.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/earntodie.apk"
    },
    {
        id: "talkingtomold",
        title: "Говорящий Том",
        desc: "мобильная игра в жанре тамагочи, аналог 2D-игры «Pou», но отличающийся от нее 3D-графическим форматом. Переведен на все языки мира. Четырнадцатая игра из серии Talking Tom and Friends. Разработана словенской компанией Outfit7 Limited.",
        author: "OutFit7",
        genre: "Тамагочи",
        rating: "4.1",
        minAndroid: "2.3.0",
        version: "1.0.19",
        screenshots: [],
        img: "img/apps/icons/talkingtomold.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/talkingtomold.apk"
    },
    {
        id: "talkingtom",
        title: "Мой Говорящий Том",
        desc: "мобильная игра в жанре тамагочи, аналог 2D-игры «Pou», но отличающийся от нее 3D-графическим форматом. Переведен на все языки мира. Четырнадцатая игра из серии Talking Tom and Friends. Разработана словенской компанией Outfit7 Limited.",
        author: "OutFit7",
        genre: "Тамагочи",
        rating: "4.4",
        minAndroid: "4.0.3",
        version: "2.2.2",
        screenshots: [],
        img: "img/apps/icons/talkingtom.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/talkingtom.apk"
    },
    {
        id: "redball4",
        title: "Red Ball 4",
        desc: "Red Ball 4 — это аркадный платформер, в котором злобные квадраты хотят превратить мир в куб. Помогите Красному шару спасти планету.",
        author: "FDG Entertainment",
        genre: "Платформеры",
        rating: "4.5",
        minAndroid: "2.3.3",
        version: "1.0.49",
        screenshots: [],
        img: "img/apps/icons/redball4.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/redball4.apk"
    },
    {
        id: "granny",
        title: "Granny",
        desc: "Granny — хоррор-игра, в которой вам нужно выбраться из дома, избегая страшной бабки.",
        author: "DVloper",
        genre: "Хорроры",
        rating: "5.0",
        minAndroid: "4.1.0",
        version: "1.7.2",
        screenshots: [],
        img: "img/apps/icons/granny.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/granny.apk"
    },
    {
        id: "hillclimbracing",
        title: "Hill Climb Racing",
        desc: "Hill Climb Racing — аркадная гоночная игра с физикой, в которой нужно забираться по холмам.",
        author: "Fingersoft",
        genre: "Гонки",
        rating: "4.8",
        minAndroid: "2.2.0",
        version: "1.20.0",
        screenshots: [],
        img: "img/apps/icons/hillclimbracing.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/hillclimbracing.apk"
    },
    {
        id: "pou",
        title: "Pou",
        desc: "Ухаживайте за своим виртуальным питомцем Pou: кормите, мойте и играйте с ним.",
        author: "Zakeh",
        genre: "Тамагочи",
        rating: "4.3",
        minAndroid: "1.6.0",
        version: "1.4.67",
        screenshots: [],
        img: "img/apps/icons/pou.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/pou.apk"
    },
    {
        id: "badpiggies",
        title: "Bad Piggies",
        desc: "Bad Piggies — головоломка от создателей Angry Birds, где вы помогаете свиньям строить транспорт.",
        author: "Rovio",
        genre: "Головоломки",
        rating: "4.6",
        minAndroid: "2.2.0",
        version: "1.1.0",
        screenshots: [],
        img: "img/apps/icons/badpiggies.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/badpiggies.apk"
    },
    {
        id: "templerun",
        title: "Temple Run",
        desc: "Temple Run — бесконечный раннер, в котором нужно убегать от монстров, собирая монеты.",
        author: "Imangi Studios",
        genre: "Раннеры",
        rating: "3.7",
        minAndroid: "2.1.0",
        version: "1.0.0",
        screenshots: [],
        img: "img/apps/icons/templerun.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/templerun.apk"
    },
    {
        id: "drdriving",
        title: "Dr. Driving",
        desc: "Dr. Driving — симулятор вождения с миссиями и заданиями в городских условиях.",
        author: "SUD Inc.",
        genre: "Симуляторы",
        rating: "4.4",
        minAndroid: "2.2.0",
        version: "1.14",
        screenshots: [],
        img: "img/apps/icons/drdriving.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/drdriving.apk"
    },
    {
        id: "veshalka",
        title: "Вешалка",
        desc: "Классическая игра «Вешалка» — угадывайте слова по буквам.",
        author: "PageNet",
        genre: "Головоломки",
        rating: "4.0",
        minAndroid: "1.5.0",
        version: "1.0.4",
        screenshots: [],
        img: "img/apps/icons/veshalka.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/veshalka.apk"
    },
    {
        id: "ppsspp",
        title: "PPSSPP",
        desc: "PPSSPP — эмулятор PSP, позволяющий запускать игры от PlayStation Portable на Android.",
        author: "Henrik Rydgård",
        genre: "Эмуляторы",
        rating: "4.8",
        minAndroid: "2.3.0",
        version: "1.18.1",
        screenshots: [],
        img: "img/apps/icons/ppsspp.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/ppsspp.apk"
    },
    {
        id: "catsimulator",
        title: "Симулятор Кота",
        desc: "Весёлый симулятор, в котором вы играете за кота и устраиваете хаос в доме и на улице.",
        author: "Koenigz",
        genre: "Симуляторы",
        rating: "4.2",
        minAndroid: "4.0.1",
        version: "2.0.2",
        screenshots: [],
        img: "img/apps/icons/catsimulator.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/catsimulator.apk"
    },
    {
        id: "robberybob",
        title: "Robbery Bob",
        desc: "Смешной стелс-экшен, в котором вы играете за неудачливого вора Боба.",
        author: "Deca Games",
        genre: "Боевики",
        rating: "4.5",
        minAndroid: "2.2.0",
        version: "1.0.3",
        screenshots: [],
        img: "img/apps/icons/robberybob.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/robberybob.apk"
    },
    {
        id: "supremeduelist",
        title: "Supreme Duelist",
        desc: "Физический файтинг с палочными человечками и безумными аренами.",
        author: "Neron's Brother",
        genre: "Файтинги",
        rating: "4.4",
        minAndroid: "4.4.0",
        version: "2.6.5",
        screenshots: [],
        img: "img/apps/icons/supremeduelist.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/supremeduelist.apk"
    },
    {
        id: "vhb",
        title: "Владик хочет бухать",
        desc: "Владик хочет бухать — смешная аркада, в которой нужно ловить бухлишко и уворачиваться от закуси. Владик так сильно страдает от нехватки алкоголя в своём организме, что готов упиться в зюзю. Помоги Владику сделать это как можно быстрее!",
        author: "GomelBall",
        genre: "Аркады",
        rating: "4.3",
        minAndroid: "2.3.0",
        version: "1.4",
        screenshots: [],
        img: "img/apps/icons/vhb.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/vhb.apk"
    },
    {
        id: "nolik",
        title: "Нолик",
        desc: "Фиксики: Говорящий Нолик - По играйте с маленьким мальчиком, Ноликом из мультфильма Фиксики. Ему скучно и он хочет с вами поиграть, по веселится ну и конечно же что нибудь починить!",
        author: "AppsMinistry",
        genre: "Аркады",
        rating: "4.5",
        minAndroid: "4.1.0",
        version: "2.4.4",
        screenshots: [],
        img: "img/apps/icons/nolik.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/nolik.apk"
    },
    {
        id: "undertale",
        title: "Undertale",
        desc: "Undertale — культовая RPG с необычной боевой системой и глубоким сюжетом.",
        author: "Toby Fox",
        genre: "RPG",
        rating: "4.8",
        minAndroid: "2.3.0",
        version: "2.0",
        screenshots: [],
        img: "img/apps/icons/undertale.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/undertale.apk"
    },
    {
        id: "baldi",
        title: "Baldi's Basics Classic",
        desc: "Хоррор-пародия на обучающие игры 90-х.",
        author: "Basically Games",
        genre: "Хорроры",
        rating: "4.8",
        minAndroid: "4.1.0",
        version: "1.4.4",
        screenshots: [],
        img: "img/apps/icons/baldi.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/baldi.apk"
    },
    {
        id: "nupogodi",
        title: "Ну, Погоди!",
        desc: "Классическая игра по мотивам знаменитого мультфильма.",
        author: "Unknown",
        genre: "Аркады",
        rating: "4.8",
        minAndroid: "1.5.0",
        version: "1.0.17",
        screenshots: [],
        img: "img/apps/icons/nupogodi.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/nupogodi.apk"
    },
    {
        id: "zombietsunami",
        title: "Zombie Tsunami",
        desc: "Аркадный раннер, где вы управляете толпой зомби.",
        author: "Mobigame",
        genre: "Раннеры",
        rating: "4.6",
        minAndroid: "4.0.3",
        version: "3.6.3",
        screenshots: [],
        img: "img/apps/icons/zombietsunami.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/zombietsunami.apk"
    },
    {
        id: "booba",
        title: "Буба",
        desc: "Игра по мотивам мультсериала «Буба».",
        author: "Kedoo",
        genre: "Тамагочи",
        rating: "4.4",
        minAndroid: "4.0.1",
        version: "1.2.2.4",
        screenshots: [],
        img: "img/apps/icons/booba.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/booba.apk"
    },
    {
        id: "talkingted",
        title: "Talking Ted",
        desc: "Говорящие персонажи на телефоне уже далеко не в диковинку, но этот медведь особенный. Кроме того что он все за Вами повторит, так он еще пьет пиво, курит и матерится.",
        author: "NBCuni",
        genre: "Тамагочи",
        rating: "4.7",
        minAndroid: "2.2.0",
        version: "2.0.3",
        screenshots: [],
        img: "img/apps/icons/talkingted.png",
        section: "apps",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/talkingted.apk"
    },
    {
        id: "kitkatquest",
        title: "KitKat Quest",
        desc: "Мини-игра Android KitKat с зелёным роботом.",
        author: "DoubleLeft",
        genre: "Аркады",
        rating: "4.5",
        minAndroid: "2.3.3",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/kitkatquest.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/kitkatquest.apk"
    },
    {
        id: "bubbu",
        title: "Bubbu",
        desc: "Виртуальный питомец — ухаживайте за котиком Bubbu.",
        author: "Bubadu",
        genre: "Тамагочи",
        rating: "4.8",
        minAndroid: "4.0.3",
        version: "1.39",
        screenshots: [],
        img: "img/apps/icons/bubbu.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/bubbu.apk"
    },
    {
        id: "sumotori",
        title: "Sumotori",
        desc: "Симулятор Сумо 2009 года теперь на вашем телефоне!",
        author: "GravitySense",
        genre: "Файтинги",
        rating: "4.1",
        minAndroid: "3.0",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/sumotori.png",
        section: "games",
        fileUrl: "https://raw.githubusercontent.com/DoiKo35/ClassicMarket/main/apps-apk/sumotori.apk"
    }
];
