const games = [
    {
        id: "fff",
        title: "Рыбалка для Друзей",
        desc: "Рыбалка для Друзей - мобильный рыболовный симулятор! Можно играть как оффлайн, так и онлайн.",
        author: "evados",
        genre: "Симуляторы",
        rating: "4.4",
        minAndroid: "2.3.3",
        version: "1.22",
        screenshots: [
            "img/apps/screenshots/fff1.jpg",
            "img/apps/screenshots/fff2.jpg"
        ],
        img: "img/apps/icons/fff.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/fff.apk"
    },
    {
        id: "kutegram",
        title: "Kutegram",
        desc: "Kutegram это неофициальный кроссплатформенный клиент на основе Qt для Telegram.",
        author: "CRX",
        genre: "Мессенджеры",
        rating: "4.1",
        minAndroid: "2.3.0",
        version: "1.0.0",
        screenshots: [
            "img/apps/screenshots/kutegram1.jpg",
            "img/apps/screenshots/kutegram2.jpg",
            "img/apps/screenshots/kutegram3.jpg"
        ],
        img: "img/apps/icons/kutegram.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/kutegram.apk"
    },
    {
        id: "youtube",
        title: "YouTube",
        desc: "Погрузитесь в мир бесконечного контента с YouTube.",
        author: "FlashBack",
        genre: "Социальные сети",
        rating: "4.8",
        minAndroid: "2.2",
        version: "2.4.4",
        screenshots: [
            "img/apps/screenshots/youtube1.jpg",
            "img/apps/screenshots/youtube2.jpg"
        ],
        img: "img/apps/icons/youtube.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/youtube.apk"
    },
    {
        id: "minecraft",
        title: "Minecraft: Pocket Edition",
        desc: "Minecraft — это строительная игра жанра песочница.",
        author: "Mojang AB",
        genre: "Песочницы",
        rating: "4.3",
        minAndroid: "2.3.0",
        version: "0.8.1",
        screenshots: [
            "img/apps/screenshots/minecraft1.jpg",
            "img/apps/screenshots/minecraft2.jpg"
        ],
        img: "img/apps/icons/minecraft.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/minecraft.apk"
    },
    {
        id: "geometrydash",
        title: "Geometry Dash",
        desc: "Практически непроходимые испытания и безумная музыка.",
        author: "RobTop",
        genre: "Платформеры",
        rating: "4.4",
        minAndroid: "2.2",
        version: "1.0",
        screenshots: [],
        img: "img/apps/icons/geometrydash.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/geometrydash.apk"
    },
    {
        id: "angrybirds",
        title: "Angry Birds",
        desc: "Стреляйте птицами по укреплениям свиней.",
        author: "Rovio",
        genre: "Головоломки",
        rating: "4.0",
        minAndroid: "1.6",
        version: "1.6.0",
        screenshots: [],
        img: "img/apps/icons/angrybirds.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/angrybirds.apk"
    },
    {
        id: "subwaysurf",
        title: "Subway Surfers",
        desc: "Уворачивайтесь от поездов и собирайте монеты.",
        author: "Kiloo",
        genre: "Раннеры",
        rating: "4.6",
        minAndroid: "2.3.3",
        version: "1.24.0",
        screenshots: [],
        img: "img/apps/icons/subwaysurf.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/subwaysurf.apk"
    },
    {
        id: "pvsz",
        title: "Plants vs Zombies",
        desc: "Защитите свой дом от орд зомби.",
        author: "PopCap",
        genre: "Стратегии",
        rating: "4.9",
        minAndroid: "1.5",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/pvsz.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/pvsz.apk"
    },
    {
        id: "doodlejump",
        title: "Doodle Jump",
        desc: "Прыгай выше и выше!",
        author: "Lima",
        genre: "Платформеры",
        rating: "4.0",
        minAndroid: "2.3.3",
        version: "1.3",
        screenshots: [],
        img: "img/apps/icons/doodlejump.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/doodlejump.apk"
    },
    {
        id: "fruitninja",
        title: "Fruit Ninja",
        desc: "Режь фрукты и ставь рекорды.",
        author: "HalfBrick",
        genre: "Боевики",
        rating: "4.9",
        minAndroid: "2.3.3",
        version: "1.9.5",
        screenshots: [],
        img: "img/apps/icons/fruitninja.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/fruitninja.apk"
    },
    {
        id: "cuttherope",
        title: "Cut The Rope",
        desc: "Накорми Ам Няма конфетами!",
        author: "ZeptoLab",
        genre: "Головоломки",
        rating: "4.7",
        minAndroid: "1.6",
        version: "1.0.0",
        screenshots: [],
        img: "img/apps/icons/cuttherope.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/cutetherope.apk"
    },
    {
        id: "flappybird",
        title: "Flappy Bird",
        desc: "Расправь крылья и лети.",
        author: "DotGears",
        genre: "Боевики",
        rating: "5",
        minAndroid: "2.2",
        version: "1.2",
        screenshots: [],
        img: "img/apps/icons/flappybird.png",
        section: "games",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/flappybird.apk"
    },
    {
        id: "flashlight",
        title: "Фонарик",
        desc: "Простой и яркий фонарик.",
        author: "Devuni",
        genre: "Утилиты",
        rating: "5",
        minAndroid: "4.1",
        version: "5.4.1",
        screenshots: [],
        img: "img/apps/icons/flashlight.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/flashlight.apk"
    },

    /* ───────────── ДОБАВЛЕННЫЕ ПРИЛОЖЕНИЯ ───────────── */

    {
        id: "chrome",
        title: "Google Chrome",
        desc: "Браузер, программа для просмотра интернет-страниц, от компании Google на основе свободного браузера Chromium и движка Blink.",
        author: "Google LLC",
        genre: "Браузеры",
        rating: "4.6",
        minAndroid: "4.0.1",
        version: "42.0",
        screenshots: [],
        img: "img/apps/icons/chrome.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/chrome.apk"
    },
    {
        id: "antutu",
        title: "AnTuTu Benchmark",
        desc: "Benchmark для теста всех основных параметров телефона.",
        author: "AnTuTu",
        genre: "Утилиты",
        rating: "4.8",
        minAndroid: "2.3",
        version: "4.0",
        screenshots: [],
        img: "img/apps/icons/antutu.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/antutu.apk"
    },
    {
        id: "esfile",
        title: "ES Проводник",
        desc: "ES File Explorer - бесплатный файловый менеджер, позволяющий: копировать, перемещать, удалять файлы, пакетное переименование файлов, выводить превью, использовать мультивыбор файлов, редактировать текстовые файлы.",
        author: "ES Global",
        genre: "Утилиты",
        rating: "4.4",
        minAndroid: "2.2",
        version: "4.0.26",
        screenshots: [],
        img: "img/apps/icons/esfile.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/esfile.apk"
    },
    {
        id: "j2meloader",
        title: "J2ME Loader",
        desc: "Запуск Java-игр/приложений (J2ME) на Android.",
        author: "Play Software",
        genre: "Эмуляторы",
        rating: "4.7",
        minAndroid: "2.3",
        version: "1.4.2",
        screenshots: [],
        img: "img/apps/icons/j2meloader.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/j2meloader.apk"
    },
    {
        id: "ibispaintx",
        title: "ibisPaint X",
        desc: "ibisPaint X - это приложение, основанное на концепции социального рисования. Вы можете опубликовать процесс рисования, чтобы разделить со всеми радость творчества.",
        author: "ibis inc.",
        genre: "Редакторы",
        rating: "4.6",
        minAndroid: "4.0.1",
        version: "3.2.1",
        screenshots: [],
        img: "img/apps/icons/ibispaintx.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/ibispaintx.apk"
    },
    {
        id: "mobizen",
        title: "Mobizen",
        desc: "Запись экрана, GIF, редактирование, все из одного приложения, Mobizen!",
        author: "RSUPPORT",
        genre: "Утилиты",
        rating: "4.2",
        minAndroid: "4.4",
        version: "3.10.7.4",
        screenshots: [],
        img: "img/apps/icons/mobizen.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/mobizen.apk"
    },
    {
        id: "tiktoklite",
        title: "TikTok Lite",
        desc: "TikTok Lite — это облегчённое глобальное видеосообщество, которое не просто развлекает. Здесь вы найдёте самые крутые короткие видео и сможете поделиться яркими моментами своей жизни со всем миром.",
        author: "TikTok",
        genre: "Социальные сети",
        rating: "4.2",
        minAndroid: "3.9",
        version: "28.6.1",
        screenshots: [],
        img: "img/apps/icons/tiktoklite.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/tiktoklite.apk"
    },
    {
        id: "wdw",
        title: "Waving Droid Widget",
        desc: "Виджет Waving Droid — это потрясающий виджет для главного экрана. Вы можете выбрать любого персонажа Android, например, кекс, пончик, эклер, мороженное Froyo, имбирный пряник, медовые соты, сэндвич с мороженым, желейные конфеты, KitKat, леденец, зефир, нугу, Oreo или пирог! Или добавить любое количество! А если не можете определиться, можете добавить всех!",
        author: "AJR",
        genre: "Виджеты",
        rating: "4.6",
        minAndroid: "2.2",
        version: "5.4",
        screenshots: [],
        img: "img/apps/icons/wdw.png",
        section: "apps",
        fileUrl: "http://github.com/DoiKo35/ClassicMarket/blob/main/apps-apk/wdw.apk"
    }
];